### ISSUE TITLE
Refatorar o código

### ISSUE THREAD

**Issue by GuilhermeMuchon** [Alanzhoffmann/Pongzera#4]

**Comment by Alanzhoffmann** [comment]
A ideia é separar cada um dos objetos em classes diferentes. Cada classe vai ter seu método de inicialização que recebe a janela como referência para poder renderizar na tela

**Comment by Alanzhoffmann** [comment]
Já estou trabalhando na refatoração dos métodos de entrada, próximo passo seria a refatoração dos objetos em si (Pad e Bola)
